animated: false
black: ''
common_path: iashjd
crystal: ''
diamond: ''
emerald: ''
firered: ''
gold: ''
heartgold: ''
order: lvl
platinum: ''
red: "Pfad f\xFCr rot"
ruby: ''
silver: ''
yellow: ''
edition_override: ''
show_nicknames: true