animated: false
black: /generation-v/black-white/
common_path: https://raw.githubusercontent.com/IntegerOverFlori/sprites/master/sprites/pokemon/versions
crystal: /generation-ii/crystal/transparent/
diamond: /generation-iv/diamond-pearl/
edition_override: ''
emerald: /generation-iii/emerald/
firered: /generation-iii/firered-leafgreen/
gold: /generation-ii/gold/transparent/
heartgold: /generation-iv/heartgold-soulsilver/
order: lvl
platinum: /generation-iv/platinum/
red: /generation-i/red-blue/transparent/
ruby: /generation-iii/ruby-sapphire/
show_nicknames: true
silver: /generation-ii/silver/transparent/
single_path_check: true
yellow: /generation-i/yellow/transparent/
