animated: 0
indeedeeaddress: localhost:43885
items: 1
itemspath: ''
nicknames: 1
obspassword: pokemon
obsport: 4444
order: DexNr.
spritespath: C:/Users/Flori/OneDrive/Dokumente/GitHub/sprites/sprites/pokemon/versions/generation-iii/emerald
